services:
  expense-tracker:
    build: .
    restart: unless-stopped
    env_file:
      - path: ${EXPENSE_TRACKER_SHARED_ENV_FILE:-.env.shared}
        required: false
      - path: ${EXPENSE_TRACKER_SHARED_SECRETS_FILE:-.env.secrets}
        required: false
      - path: ${EXPENSE_TRACKER_ENV_FILE:-.env}
        required: false
    volumes:
      - ./data:/app/data
    networks:
      - default
      - observability

networks:
  observability:
    external: true
